### ISSUE TITLE
Compatibility with PHP 7

### ISSUE THREAD

**Issue by sladg** [crwlrsoft/query-string#4]
Heya!
as I'm integrating your package into Bref, we are seeing failed pipelines as PHP 7 is not supported and thus, composer fails to install.

Is there a reason to not support PHP 7?

https://github.com/brefphp/bref/pull/1437
https://github.com/brefphp/bref/actions/runs/4325550160/jobs/7564117373

**Comment by mnapoli** [comment]
Oh… We're dropping support for PHP 7.4 in Bref 2.0, which is a few days away.

Maybe what we could do is change https://github.com/brefphp/bref/pull/1437 to target Bref's v2 branch instead? I don't think supporting PHP 7 makes sense.

**Comment by otsch** [comment]
Ah, thx for stepping in @mnapoli 
I agree that it's probably best to target Bref v2 instead as PHP 7.4 is already end of life and the package is also already using PHP 8 features like union types. Hope that's OK for you.

**Comment by mnapoli** [comment]
Makes total sense 👍
